Absolut path done
Teaching-projects/SZE-MoSzE-2019-Tristania pull request #5
Opened 2019-10-18 13:21 UTC by gaborka98

2019-10-24 09:14 UTC, hegyhati requested changes

2019-10-24 09:14 UTC, hegyhati commented on File.cpp
> +File::File(std::string filename, Dir* parent, std::string content) : name(filename), parent(parent), content(content) {}
Ennek mi koze az absolute path branchhez? Ennek kulon branchben a helye.

2019-10-24 09:14 UTC, hegyhati commented on .circleci/config.yml
> +#            - build
Nem ez a megoldas, hanem az, hogy ne legyen infinite loop.

2019-10-28 08:53 UTC, hegyhati commented
@gaborka98 majd ird meg, mikor nezzem ujra, nyilvan nem fesulom at minden commit utan :-)

2019-10-28 08:58 UTC, gaborka98 commented
@hegyhati Kijavítottam a hibákat amiket írtál és a circle ci-t is megoldottam. Elvileg így kész van minden.

2019-10-28 11:16 UTC, hegyhati requested changes
CI config rendben, de a konyvtarszerkezet kezelest rendbe kell tenni. Nem usszatok meg a fat.;-)

2019-10-28 11:16 UTC, hegyhati commented on File.hpp
> +    Dir* getParent();
Ez a konstruktort leszamitva teljesen ugyanaz, mint a Dir. Nemileg adodik, hogy a kozos mukodes ki legyen szervezve egy ososztalyba :-)

2019-10-28 11:16 UTC, hegyhati commented on Dir.hpp
> +};
Azt nem latom, hogy hol tarolja, hogy milyen alkonyvtarai vannak.

2019-10-28 11:16 UTC, hegyhati commented on System.cpp
>  		}
Na azert ez igy nem teljesen oke. Ha van egy `a` meg egy `b`, amiben van egy `a`, akkor eleg renddesen osszezavarodik.

2019-10-28 11:16 UTC, hegyhati commented on System.cpp
> +    while (currentFolder->getDirName() != "root") {
es hal letrehozok egy `root` nevu konyvtarat?

2019-10-28 11:16 UTC, hegyhati commented on System.cpp
> +
Ez ha minden igaz, lekezeli a `/ize/bize` tipusu dolgokat. De mi van a `mize/bize/`-vel meg a `../ize`-vel?

2019-11-01 13:20 UTC, gaborka98 commented
@hegyhati elkészültem a programunk átdolgozásával a Dir classhoz csináltam egy children vectort és ennek megfeleően az összes fv-t átirtam. Lefutott a CCI is megfelelően. Elég sokat teszteltem szerintem mindenféle lehetőséget megnéztem, de elképzelhető, hogy akad benne még hiba.

2019-11-04 10:49 UTC, hegyhati requested changes
Komment szemeteket szedjetek ki. A "maradjon meg kesobbiekre, hatha kell" dologra ott a git history. (de nem fog kelleni ;-) ) Aztan bemehet.

2019-11-04 16:11 UTC, merged